site_name: Hardik Sankhla Academy
site_url: https://hardik-sankhla.github.io
repo_url: https://github.com/Hardik-Sankhla/Hardik-Sankhla

theme:
  name: material

nav:
  - Home: ../apps/docs/docs/index.md
  - Projects: ../apps/docs/docs/projects.md

markdown_extensions:
  - admonition
  - toc
