site_name: Hardik Sankhla Academy
site_url: https://hardik-sankhla.github.io
repo_url: https://github.com/Hardik-Sankhla/Hardik-Sankhla
docs_dir: ../apps/docs/docs

theme:
  name: material

nav:
  - Home: index.md
  - Guides:
    - Guides Overview: guides.md
  - Projects:
    - Projects Overview: projects.md
  - Courses:
    - Courses Overview: courses.md

markdown_extensions:
  - admonition
  - toc
